strategy: "RoundRobin"
ports:
  - 8080
  - 8081
  - 8082
services: 
  - matcher: "/api/v1"
    name: "test service"
    replicas:
      - "http://localhost:9090"
      - "http://localhost:9091"
      - "http://localhost:9092"