# wrr : Weighted Round Robin
strategy: "wrr"
max_connections: 1024
# random ports for testing/development purposes
ports:
  - 8080
  - 8081
  - 8082
services: 
  - matcher: "/api/v1"
    name: "test service"
    replicas:
      - url: "http://localhost:9090"
        metadata:
          weight: 10
      - url: "http://localhost:9091"
        metadata:
          weight: 1
      - url: "http://localhost:9092"
        metadata:
          weight: 1
  - matcher: "/api/v2"
    name: "another service"
    replicas:
      - url: "http://localhost:9093"
        metadata:
          weight: 10
      - url: "http://localhost:9094"
        metadata:
          weight: 1
      - url: "http://localhost:9095"
        metadata:
          weight: 1